// Static Grayscale language data: keywords, types, builtins, stdlib modules, and hover docs.
// Source of truth: Grayscale STANDARD.md

export const KEYWORDS: string[] = [
  // Control flow
  'as_long_as', 'break', 'continue', 'default', 'else', 'ensure', 'for', 'for_each',
  'if', 'is', 'loop', 'or', 'or_return', 'otherwise', 'return', 'when', 'while',
  // Declarations
  'const', 'do', 'enum', 'import', 'mut', 'new', 'private', 'struct', 'use', 'using',
  // Operators / values
  'bit_and', 'bit_not', 'bit_or', 'bit_shift_left', 'bit_shift_right', 'bit_xor',
  'cast', 'false', 'in', 'not_in', 'nil', 'range', 'true',
];

export const TYPES: string[] = [
  // Primitive
  'bool', 'byte', 'char', 'Error', 'float', 'func', 'int', 'map', 'string', 'uint',
  // Sized integers
  'i8', 'i16', 'i32', 'i64', 'i128', 'i256',
  'u8', 'u16', 'u32', 'u64', 'u128', 'u256',
  // Sized floats
  'f32', 'f64',
];

export const BUILTINS: string[] = [
  // Output
  'println', 'print', 'eprintln', 'eprint',
  // Input
  'input',
  // Collections / memory
  'len', 'copy', 'new', 'ref', 'addr',
  // Type utilities
  'type_of', 'size_of', 'cast',
  // String utilities
  'to_char', 'char_count', 'c_string',
  // Error / control
  'error', 'assert', 'panic', 'exit',
  // Range
  'range',
  // Wide integer constructors
  'i128', 'i256', 'u128', 'u256',
  // Compile-time
  'embed',
  // Sleep
  'sleep_s', 'sleep_ms', 'sleep_ns',
  // Type conversion functions (also serve as cast)
  'int', 'uint', 'float', 'string', 'bool',
];

export const STDLIB_MODULES: string[] = [
  'arrays', 'strings', 'maps', 'math', 'time', 'random',
  'json', 'io', 'os', 'http', 'crypto', 'encoding',
  'uuid', 'bytes', 'binary', 'sqlite', 'server', 'regex', 'csv',
  'net', 'threads', 'sync', 'channels', 'mem', 'atomic', 'fmt', 'strconv',
];

export const ATTRIBUTES: string[] = [
  'doc', 'json', 'flags', 'strict', 'discard',
];

// ---------------------------------------------------------------------------
// Stdlib module → function docs
// Key format: "module.function"  (e.g. "arrays.append")
// ---------------------------------------------------------------------------

export const MODULE_FUNCTION_DOCS: Record<string, string> = {
  // @arrays
  'arrays.is_empty':    '**`arrays.is_empty(arr [T]) -> bool`** — Check if array is empty.',
  'arrays.contains':    '**`arrays.contains(arr [T], value T) -> bool`** — Check if value exists in array.',
  'arrays.index_of':    '**`arrays.index_of(arr [T], value T) -> int`** — First index of value, or -1 if not found.',
  'arrays.count':       '**`arrays.count(arr [T], value T) -> int`** — Count occurrences of value.',
  'arrays.is_equal':    '**`arrays.is_equal(a [T], b [T]) -> bool`** — Structural equality (use instead of `==`).',
  'arrays.get_first':   '**`arrays.get_first(arr [T]) -> T`** — Return first element (panics if empty).',
  'arrays.get_last':    '**`arrays.get_last(arr [T]) -> T`** — Return last element (panics if empty).',
  'arrays.append':      '**`arrays.append(&arr [T], value T)`** — Append an element to the end of the array.',
  'arrays.prepend':     '**`arrays.prepend(&arr [T], value T)`** — Insert value at the front.',
  'arrays.insert_at':   '**`arrays.insert_at(&arr [T], index int, value T)`** — Insert value at index.',
  'arrays.remove':      '**`arrays.remove(&arr [T], value T)`** — Remove first occurrence of value.',
  'arrays.remove_at':   '**`arrays.remove_at(&arr [T], index int)`** — Remove element at index.',
  'arrays.remove_first':'**`arrays.remove_first(&arr [T]) -> T`** — Remove and return first element.',
  'arrays.remove_last': '**`arrays.remove_last(&arr [T]) -> T`** — Remove and return last element.',
  'arrays.clear':       '**`arrays.clear(&arr [T])`** — Remove all elements.',
  'arrays.fill':        '**`arrays.fill(&arr [T], value T, count int)`** — Fill array with N copies of value.',
  'arrays.sort_asc':    '**`arrays.sort_asc(&arr [T])`** — Sort ascending in-place.',
  'arrays.sort_desc':   '**`arrays.sort_desc(&arr [T])`** — Sort descending in-place.',
  'arrays.reverse':     '**`arrays.reverse(arr [T]) -> [T]`** — Return a reversed copy.',
  'arrays.slice':       '**`arrays.slice(arr [T], start int, end int) -> [T]`** — Return a slice.',
  'arrays.concat':      '**`arrays.concat(a [T], b [T]) -> [T]`** — Concatenate two arrays.',
  'arrays.deduplicate': '**`arrays.deduplicate(arr [T]) -> [T]`** — Remove duplicate values.',
  'arrays.flatten':     '**`arrays.flatten(arr [[T]]) -> [T]`** — Flatten one level of nesting.',
  'arrays.split_every': '**`arrays.split_every(arr [T], size int) -> [[T]]`** — Split into sub-arrays of given size.',
  'arrays.pair':        '**`arrays.pair(a [T], b [T]) -> [[T]]`** — Pair elements from two arrays.',
  'arrays.get_sum':     '**`arrays.get_sum(arr [T]) -> T`** — Sum all elements.',
  'arrays.get_min':     '**`arrays.get_min(arr [T]) -> T`** — Minimum element.',
  'arrays.get_max':     '**`arrays.get_max(arr [T]) -> T`** — Maximum element.',
  'arrays.map':         '**`arrays.map(arr [T], ()transform) -> [T]`** — Return new array with transform applied to each element.',
  'arrays.filter':      '**`arrays.filter(arr [T], ()predicate) -> [T]`** — Return elements for which predicate returns true.',
  'arrays.reduce':      '**`arrays.reduce(arr [T], initial T, ()accumulator) -> T`** — Reduce array to a single value.',
  'arrays.any':         '**`arrays.any(arr [T], ()predicate) -> bool`** — True if at least one element satisfies predicate. Returns false on empty array.',
  'arrays.all':         '**`arrays.all(arr [T], ()predicate) -> bool`** — True if every element satisfies predicate. Returns true on empty array.',

  // @strings
  'strings.to_upper':      '**`strings.to_upper(s string) -> string`** — Convert to uppercase.',
  'strings.to_lower':      '**`strings.to_lower(s string) -> string`** — Convert to lowercase.',
  'strings.char_at':       '**`strings.char_at(s string, index int) -> char`** — Character at byte index; panics if out of bounds.',
  'strings.is_empty':      '**`strings.is_empty(s string) -> bool`** — Check if string is empty (zero length).',
  'strings.contains':      '**`strings.contains(s string, sub string) -> bool`** — Check if string contains substring.',
  'strings.starts_with':   '**`strings.starts_with(s string, prefix string) -> bool`** — Check if string starts with prefix.',
  'strings.ends_with':     '**`strings.ends_with(s string, suffix string) -> bool`** — Check if string ends with suffix.',
  'strings.index_of':      '**`strings.index_of(s string, sub string) -> int`** — First index of substring.',
  'strings.last_index_of': '**`strings.last_index_of(s string, sub string) -> int`** — Last index of substring (-1 if not found).',
  'strings.count':         '**`strings.count(s string, sub string) -> int`** — Count occurrences of substring.',
  'strings.is_alpha':      '**`strings.is_alpha(c char) -> bool`** — True if c is an ASCII letter (a-z, A-Z).',
  'strings.is_digit':      '**`strings.is_digit(c char) -> bool`** — True if c is a decimal digit (0-9).',
  'strings.is_alnum':      '**`strings.is_alnum(c char) -> bool`** — True if c is a letter or digit.',
  'strings.is_whitespace': '**`strings.is_whitespace(c char) -> bool`** — True if c is space, tab, newline, or CR.',
  'strings.is_upper':      '**`strings.is_upper(c char) -> bool`** — True if c is an uppercase letter.',
  'strings.is_lower':      '**`strings.is_lower(c char) -> bool`** — True if c is a lowercase letter.',
  'strings.trim':          '**`strings.trim(s string) -> string`** — Trim leading and trailing whitespace.',
  'strings.trim_left':     '**`strings.trim_left(s string) -> string`** — Trim leading whitespace.',
  'strings.trim_right':    '**`strings.trim_right(s string) -> string`** — Trim trailing whitespace.',
  'strings.remove_prefix': '**`strings.remove_prefix(s string, prefix string) -> string`** — Remove prefix if present, otherwise return unchanged.',
  'strings.remove_suffix': '**`strings.remove_suffix(s string, suffix string) -> string`** — Remove suffix if present, otherwise return unchanged.',
  'strings.replace':       '**`strings.replace(s string, old string, new string) -> string`** — Replace all occurrences.',
  'strings.repeat':        '**`strings.repeat(s string, count int) -> string`** — Repeat string N times.',
  'strings.reverse':       '**`strings.reverse(s string) -> string`** — Reverse string.',
  'strings.split':         '**`strings.split(s string, sep string) -> [string]`** — Split string by separator.',
  'strings.join':          '**`strings.join(arr [string], sep string) -> string`** — Join array of strings with separator.',
  'strings.slice':         '**`strings.slice(s string, start int, end int) -> string`** — Extract substring by byte index.',
  'strings.to_chars':      '**`strings.to_chars(s string) -> [char]`** — Convert string to char array.',
  'strings.from_chars':    '**`strings.from_chars(chars [char]) -> string`** — Convert char array to string.',

  // @maps
  'maps.is_empty':        '**`maps.is_empty(m map[K:V]) -> bool`** — Check if map is empty.',
  'maps.has_key':         '**`maps.has_key(m map[K:V], key K) -> bool`** — Check if key exists.',
  'maps.contains_value':  '**`maps.contains_value(m map[K:V], value V) -> bool`** — Check if any entry has the given value.',
  'maps.get_keys':        '**`maps.get_keys(m map[K:V]) -> [K]`** — Get all keys as an array.',
  'maps.get_values':      '**`maps.get_values(m map[K:V]) -> [V]`** — Get all values as an array.',
  'maps.get_or_default':  '**`maps.get_or_default(m map[K:V], key K, default V) -> V`** — Get value or return default if key missing.',
  'maps.remove_key':      '**`maps.remove_key(&m map[K:V], key K)`** — Remove key-value pair; does nothing if key absent.',
  'maps.clear':           '**`maps.clear(&m map[K:V])`** — Remove all entries.',
  'maps.merge':           '**`maps.merge(m1 map[K:V], m2 map[K:V]) -> map[K:V]`** — Combine two maps (m2 overwrites on conflict).',
  'maps.is_equal':        '**`maps.is_equal(a map[K:V], b map[K:V]) -> bool`** — Structural equality (use instead of `==`).',

  // @math
  'math.abs':       '**`math.abs(n T) -> T`** — Absolute value.',
  'math.neg':       '**`math.neg(n T) -> T`** — Negation.',
  'math.sign':      '**`math.sign(n T) -> int`** — Sign: -1, 0, or 1.',
  'math.min':       '**`math.min(a T, b T) -> T`** — Minimum of two values.',
  'math.max':       '**`math.max(a T, b T) -> T`** — Maximum of two values.',
  'math.clamp':     '**`math.clamp(value T, min T, max T) -> T`** — Clamp value to range [min, max].',
  'math.floor':     '**`math.floor(n T) -> float`** — Round down to nearest integer.',
  'math.ceil':      '**`math.ceil(n T) -> float`** — Round up to nearest integer.',
  'math.round':     '**`math.round(n T) -> float`** — Round to nearest integer.',
  'math.trunc':     '**`math.trunc(n T) -> float`** — Truncate toward zero.',
  'math.pow':       '**`math.pow(base T, exp T) -> float`** — Raise base to exponent.',
  'math.sqrt':      '**`math.sqrt(n T) -> float`** — Square root.',
  'math.cbrt':      '**`math.cbrt(n T) -> float`** — Cube root.',
  'math.hypot':     '**`math.hypot(x T, y T) -> float`** — Hypotenuse: sqrt(x² + y²).',
  'math.exp':       '**`math.exp(n T) -> float`** — e raised to the power n.',
  'math.exp2':      '**`math.exp2(n T) -> float`** — 2 raised to the power n.',
  'math.log':       '**`math.log(n T) -> float`** — Natural logarithm.',
  'math.log2':      '**`math.log2(n T) -> float`** — Base-2 logarithm.',
  'math.log10':     '**`math.log10(n T) -> float`** — Base-10 logarithm.',
  'math.log_base':  '**`math.log_base(value T, base T) -> float`** — Logarithm with custom base.',
  'math.sin':       '**`math.sin(rad T) -> float`** — Sine (radians).',
  'math.cos':       '**`math.cos(rad T) -> float`** — Cosine (radians).',
  'math.tan':       '**`math.tan(rad T) -> float`** — Tangent (radians).',
  'math.asin':      '**`math.asin(n T) -> float`** — Arc sine.',
  'math.acos':      '**`math.acos(n T) -> float`** — Arc cosine.',
  'math.atan':      '**`math.atan(n T) -> float`** — Arc tangent.',
  'math.atan2':     '**`math.atan2(y T, x T) -> float`** — Arc tangent of y/x.',
  'math.sinh':      '**`math.sinh(n T) -> float`** — Hyperbolic sine.',
  'math.cosh':      '**`math.cosh(n T) -> float`** — Hyperbolic cosine.',
  'math.tanh':      '**`math.tanh(n T) -> float`** — Hyperbolic tangent.',
  'math.deg_to_rad':'**`math.deg_to_rad(deg T) -> float`** — Convert degrees to radians.',
  'math.rad_to_deg':'**`math.rad_to_deg(rad T) -> float`** — Convert radians to degrees.',
  'math.factorial': '**`math.factorial(n int) -> int`** — Factorial (n must be non-negative).',
  'math.gcd':       '**`math.gcd(a int, b int) -> int`** — Greatest common divisor.',
  'math.lcm':       '**`math.lcm(a int, b int) -> int`** — Least common multiple.',
  'math.is_prime':  '**`math.is_prime(n int) -> bool`** — Check if number is prime.',
  'math.is_even':   '**`math.is_even(n int) -> bool`** — Check if number is even.',
  'math.is_odd':    '**`math.is_odd(n int) -> bool`** — Check if number is odd.',
  'math.is_infinite':'**`math.is_infinite(n float) -> bool`** — Check if value is infinite.',
  'math.is_nan':    '**`math.is_nan(n float) -> bool`** — Check if value is NaN.',
  'math.is_finite': '**`math.is_finite(n float) -> bool`** — Check if value is finite (not infinite or NaN).',
  'math.lerp':      '**`math.lerp(a T, b T, t T) -> float`** — Linear interpolation between a and b by factor t.',
  'math.distance':  '**`math.distance(x1 T, y1 T, x2 T, y2 T) -> float`** — Euclidean distance between two 2D points.',

  // @time
  'time.now':        '**`time.now() -> int`** — Current Unix timestamp in seconds.',
  'time.now_ms':     '**`time.now_ms() -> int`** — Current Unix timestamp in milliseconds.',
  'time.now_ns':     '**`time.now_ns() -> int`** — Current Unix timestamp in nanoseconds.',
  'time.year':       '**`time.year(timestamp int) -> int`** — Get year from Unix timestamp.',
  'time.month':      '**`time.month(timestamp int) -> int`** — Get month (1–12) from Unix timestamp.',
  'time.day':        '**`time.day(timestamp int) -> int`** — Get day of month from Unix timestamp.',
  'time.hour':       '**`time.hour(timestamp int) -> int`** — Get hour from Unix timestamp.',
  'time.minute':     '**`time.minute(timestamp int) -> int`** — Get minute from Unix timestamp.',
  'time.second':     '**`time.second(timestamp int) -> int`** — Get second from Unix timestamp.',
  'time.weekday':    '**`time.weekday(timestamp int) -> int`** — Get day of week (0=Sunday).',
  'time.format':     '**`time.format(format string, timestamp int) -> string`** — Format timestamp with a format string.',
  'time.to_iso':     '**`time.to_iso(timestamp int) -> string`** — Format as ISO 8601 string.',
  'time.date':       '**`time.date(timestamp int) -> string`** — Format as YYYY-MM-DD.',
  'time.to_clock':   '**`time.to_clock(timestamp int) -> string`** — Format as HH:MM:SS.',
  'time.diff':       '**`time.diff(t1 int, t2 int) -> int`** — Difference in seconds (t2 - t1); negative if t1 is after t2.',
  'time.tick':       '**`time.tick() -> int`** — High-resolution timestamp in nanoseconds (for performance timing).',
  'time.elapsed_ms': '**`time.elapsed_ms(start_tick int) -> int`** — Milliseconds elapsed since a `time.tick()` call.',

  // @random
  'random.rand_float':  '**`random.rand_float() -> float`** — Random float in [0.0, 1.0).\n\n**`random.rand_float(min float, max float) -> float`** — Random float in [min, max).',
  'random.rand_int':    '**`random.rand_int(max int) -> int`** — Random int in [0, max).\n\n**`random.rand_int(min int, max int) -> int`** — Random int in [min, max).',
  'random.rand_bool':   '**`random.rand_bool() -> bool`** — Random boolean.',
  'random.rand_byte':   '**`random.rand_byte() -> byte`** — Random byte in [0, 255].',
  'random.rand_char':   '**`random.rand_char() -> char`** — Random printable char.\n\n**`random.rand_char(min char, max char) -> char`** — Random char in range.',
  'random.choice':      '**`random.choice(arr [T]) -> T`** — Random element from array.',
  'random.shuffle':     '**`random.shuffle(arr [T]) -> [T]`** — Return shuffled copy of array.',
  'random.sample':      '**`random.sample(arr [T], n int) -> [T]`** — Return n unique random elements.',
  'random.seed':        '**`random.seed(value int)`** — Seed the random number generator.',

  // @io
  'io.read_file':     '**`io.read_file(path string) -> string`** — Read entire file as a string.',
  'io.read_bytes':    '**`io.read_bytes(path string) -> [byte]`** — Read entire file as a byte array.',
  'io.read_lines':    '**`io.read_lines(path string) -> [string]`** — Read file and split into lines.',
  'io.write_file':    '**`io.write_file(path string, content string) -> bool`** — Write content to file (overwrite).',
  'io.append_file':   '**`io.append_file(path string, content string) -> bool`** — Append content to file.',
  'io.file_exists':   '**`io.file_exists(path string) -> bool`** — Check if file exists.',
  'io.is_file':       '**`io.is_file(path string) -> bool`** — Check if path is a regular file.',
  'io.is_directory':  '**`io.is_directory(path string) -> bool`** — Check if path is a directory.',
  'io.file_size':     '**`io.file_size(path string) -> int`** — Get file size in bytes; returns -1 on error.',
  'io.delete_file':   '**`io.delete_file(path string) -> bool`** — Delete file.',
  'io.rename_file':   '**`io.rename_file(old_path string, new_path string) -> bool`** — Rename file.',
  'io.copy_file':     '**`io.copy_file(src string, dst string) -> bool`** — Copy file.',
  'io.move_file':     '**`io.move_file(src string, dst string) -> bool`** — Move file.',
  'io.list_dir':      '**`io.list_dir(path string) -> [string]`** — List directory entries.',
  'io.make_dir':      '**`io.make_dir(path string) -> bool`** — Create directory.',
  'io.make_dir_all':  '**`io.make_dir_all(path string) -> bool`** — Create directory and all parents.',
  'io.remove_dir':    '**`io.remove_dir(path string) -> bool`** — Remove empty directory.',
  'io.remove_dir_all':'**`io.remove_dir_all(path string) -> bool`** — Remove directory and all contents.',
  'io.walk':          '**`io.walk(path string) -> [string]`** — Recursively list all files.',
  'io.glob':          '**`io.glob(pattern string) -> [string]`** — Match files by glob pattern.',
  'io.path_join':     '**`io.path_join(parts [string]) -> string`** — Join path segments.',
  'io.dirname':       '**`io.dirname(path string) -> string`** — Parent directory of path.',
  'io.basename':      '**`io.basename(path string) -> string`** — Filename component of path.',
  'io.extension':     '**`io.extension(path string) -> string`** — File extension including dot (e.g. ".txt").',
  'io.is_absolute':   '**`io.is_absolute(path string) -> bool`** — Check if path is absolute.',
  'io.normalize':     '**`io.normalize(path string) -> string`** — Clean and normalize path.',

  // @os
  'os.get_env':     '**`os.get_env(name string) -> string`** — Get environment variable value.',
  'os.set_env':     '**`os.set_env(name string, value string)`** — Set environment variable.',
  'os.unset_env':   '**`os.unset_env(name string)`** — Remove environment variable.',
  'os.args':        '**`os.args() -> [string]`** — Command-line arguments.',
  'os.current_dir': '**`os.current_dir() -> string`** — Get current working directory.',
  'os.hostname':    '**`os.hostname() -> string`** — Get machine hostname.',
  'os.pid':         '**`os.pid() -> int`** — Get process ID.',
  'os.current_os':  '**`os.current_os() -> int`** — Get current OS (MAC_OS=0, LINUX=1, WINDOWS=2, OTHER=3).',
  'os.arch':        '**`os.arch() -> string`** — Get CPU architecture.',
  'os.exec':        '**`os.exec(cmd string, args [string]) -> (int, string, string, bool)`** — Run subprocess. Returns (exit_code, stdout, stderr, ok).',

  // @json
  'json.decode':       '**`json.decode(text string) -> map[string:string]`** — Decode JSON string to map.',
  'json.parse':        '**`json.parse(text string) -> T`** — Parse JSON into a `#json` struct.',
  'json.encode':       '**`json.encode(value T) -> string`** — Encode value to JSON string.',
  'json.stringify':    '**`json.stringify(value T) -> string`** — Encode to JSON string (supports `#json` structs).',
  'json.pretty_print': '**`json.pretty_print(m map, indent int) -> string`** — Pretty-print a map as indented JSON.',
  'json.is_valid':     '**`json.is_valid(text string) -> bool`** — Check if valid JSON.',

  // @uuid
  'uuid.generate':              '**`uuid.generate() -> UUID`** — Generate UUID v4 (hyphenated, 36 chars).',
  'uuid.generate_hyphenated':   '**`uuid.generate_hyphenated() -> UUID`** — Alias for `generate`.',
  'uuid.generate_random':       '**`uuid.generate_random() -> UUID`** — RFC 4122 v4 (random), hyphenated, lowercase.',
  'uuid.generate_time_ordered': '**`uuid.generate_time_ordered() -> UUID`** — RFC 9562 v7 (time-ordered). Sorts by creation time.',
  'uuid.generate_compact':      '**`uuid.generate_compact(id UUID) -> string`** — Strip hyphens, returning a 32-char hex string.',
  'uuid.parse':                 '**`uuid.parse(s string) -> UUID`** — Validate and normalize a UUID. Panics on invalid input.',
  'uuid.to_string':             '**`uuid.to_string(id UUID) -> string`** — Convert UUID to its 36-char hyphenated string.',
  'uuid.is_valid':              '**`uuid.is_valid(s string) -> bool`** — Validate UUID format.',

  // @regex
  'regex.is_valid':  '**`regex.is_valid(pattern string) -> bool`** — Check if pattern is valid regex.',
  'regex.is_match':  '**`regex.is_match(pattern string, text string) -> bool`** — Check if pattern matches text.',
  'regex.find':      '**`regex.find(pattern string, text string) -> string`** — First match.',
  'regex.find_all':  '**`regex.find_all(pattern string, text string) -> [string]`** — All matches.',
  'regex.replace':   '**`regex.replace(pattern string, text string, replacement string) -> string`** — Replace matches.',
  'regex.split':     '**`regex.split(pattern string, text string) -> [string]`** — Split by pattern.',

  // @crypto
  'crypto.sha256':     '**`crypto.sha256(data string) -> string`** — SHA-256 hash (hex).',
  'crypto.md5':        '**`crypto.md5(data string) -> string`** — MD5 hash (hex).',
  'crypto.random_hex': '**`crypto.random_hex(length int) -> string`** — Cryptographically secure random hex string.',

  // @encoding
  'encoding.base64_encode': '**`encoding.base64_encode(s string) -> string`** — Encode to Base64.',
  'encoding.base64_decode': '**`encoding.base64_decode(s string) -> string`** — Decode from Base64.',
  'encoding.hex_encode':    '**`encoding.hex_encode(s string) -> string`** — Encode to hex string.',
  'encoding.hex_decode':    '**`encoding.hex_decode(s string) -> string`** — Decode from hex string.',
  'encoding.url_encode':    '**`encoding.url_encode(s string) -> string`** — URL percent-encode.',
  'encoding.url_decode':    '**`encoding.url_decode(s string) -> string`** — URL percent-decode.',

  // @http
  'http.get':    '**`http.get(url string, headers map[string:string]) -> HttpResponse`** — GET request.',
  'http.post':   '**`http.post(url string, body string, headers map[string:string]) -> HttpResponse`** — POST request.',
  'http.put':    '**`http.put(url string, body string, headers map[string:string]) -> HttpResponse`** — PUT request.',
  'http.patch':  '**`http.patch(url string, body string, headers map[string:string]) -> HttpResponse`** — PATCH request.',
  'http.delete': '**`http.delete(url string, headers map[string:string]) -> HttpResponse`** — DELETE request.',
  'http.head':   '**`http.head(url string, headers map[string:string]) -> HttpResponse`** — HEAD request.',

  // @bytes
  'bytes.from_string': '**`bytes.from_string(s string) -> [byte]`** — Create from UTF-8 string.',
  'bytes.from_hex':    '**`bytes.from_hex(hex string) -> [byte]`** — Decode hex string.',
  'bytes.from_base64': '**`bytes.from_base64(b64 string) -> [byte]`** — Decode base64 string.',
  'bytes.to_string':   '**`bytes.to_string(bytes [byte]) -> string`** — Convert to UTF-8 string.',
  'bytes.to_hex':      '**`bytes.to_hex(bytes [byte]) -> string`** — Encode to hex string.',
  'bytes.to_base64':   '**`bytes.to_base64(bytes [byte]) -> string`** — Encode to base64 string.',

  // @sqlite
  'sqlite.open':  '**`sqlite.open(path string) -> (Database, Error)`** — Open or create a SQLite database.',
  'sqlite.close': '**`sqlite.close(db Database)`** — Close database connection.',
  'sqlite.exec':  '**`sqlite.exec(db Database, sql string) -> (bool, Error)`** — Execute a SQL statement (no rows returned).',
  'sqlite.query': '**`sqlite.query(db Database, sql string) -> ([map[string:string]], Error)`** — Execute a SELECT query.',

  // @server
  'server.add_router': '**`server.add_router() -> Router`** — Create a new router.',
  'server.add_route':  '**`server.add_route(router Router, method string, path string, ()handler)`** — Add a route with handler function.',
  'server.listen':     '**`server.listen(router Router, port int)`** — Start HTTP server on port (blocks).',
  'server.cors':       '**`server.cors(router Router, origin string)`** — Enable CORS with the given origin.',
  'server.use':        '**`server.use(router Router, ()middleware)`** — Register a middleware function.',
  'server.text':       '**`server.text(status int, body string) -> HttpResponse`** — Create text/plain response.',
  'server.json':       '**`server.json(status int, data) -> HttpResponse`** — Create application/json response.',
  'server.html':       '**`server.html(status int, body string) -> HttpResponse`** — Create text/html response.',
  'server.redirect':   '**`server.redirect(status int, url string) -> HttpResponse`** — Create redirect response.',

  // @csv
  'csv.parse':      '**`csv.parse(csv_string string) -> [[string]]`** — Parse CSV string to 2D array.',
  'csv.encode':     '**`csv.encode(data [[string]]) -> string`** — Encode 2D array to CSV string.',
  'csv.read_file':  '**`csv.read_file(path string) -> ([[string]], Error)`** — Read and parse CSV file.',
  'csv.write_file': '**`csv.write_file(path string, data [[string]]) -> (bool, Error)`** — Write 2D array to CSV file.',
  'csv.headers':    '**`csv.headers(data [[string]]) -> [string]`** — Extract header row from parsed CSV data.',

  // @net
  'net.connect':     '**`net.connect(host string, port int) -> Socket`** — Connect to a remote host.',
  'net.listen':      '**`net.listen(port int) -> Listener`** — Listen for incoming connections.',
  'net.accept':      '**`net.accept(listener Listener) -> Socket`** — Accept an incoming connection.',
  'net.send':        '**`net.send(sock Socket, data string) -> int`** — Send data, returns bytes sent.',
  'net.receive':     '**`net.receive(sock Socket, max_bytes int) -> string`** — Receive up to max_bytes.',
  'net.close':       '**`net.close(sock Socket)`** — Close a socket or listener.',
  'net.set_timeout': '**`net.set_timeout(sock Socket, ms int)`** — Set read/write timeout in milliseconds.',
  'net.resolve':     '**`net.resolve(hostname string) -> string`** — Resolve hostname to IP address.',

  // @threads
  'threads.spawn':        '**`threads.spawn(()func) -> Thread`** — Spawn a new thread running func.',
  'threads.join':         '**`threads.join(t Thread)`** — Wait for a thread to finish.',
  'threads.detach':       '**`threads.detach(t Thread)`** — Release ownership; thread runs independently.',
  'threads.is_alive':     '**`threads.is_alive(t Thread) -> bool`** — True while the thread has not returned.',
  'threads.get_id':       '**`threads.get_id() -> int`** — Get the current thread\'s ID.',
  'threads.current':      '**`threads.current() -> int`** — Get the current thread\'s ID (alias for get_id).',
  'threads.yield':        '**`threads.yield()`** — Hint the scheduler to run another thread.',
  'threads.sleep':        '**`threads.sleep(ms int)`** — Sleep the current thread for ms milliseconds.',
  'threads.thread_count': '**`threads.thread_count() -> int`** — Number of live spawned threads.',

  // @sync
  'sync.mutex':    '**`sync.mutex() -> Mutex`** — Create a new mutex.',
  'sync.lock':     '**`sync.lock(m Mutex)`** — Acquire a mutex.',
  'sync.unlock':   '**`sync.unlock(m Mutex)`** — Release a mutex.',
  'sync.try_lock': '**`sync.try_lock(m Mutex)`** — Try to acquire a mutex (non-blocking).',
  'sync.destroy':  '**`sync.destroy(m Mutex)`** — Destroy a mutex.',

  // @channels
  'channels.open':        '**`channels.open(capacity int) -> Channel`** — Create a buffered channel.',
  'channels.send':        '**`channels.send(ch Channel, value)`** — Send a value into a channel.',
  'channels.receive':     '**`channels.receive(ch Channel) -> T`** — Receive a value from a channel.',
  'channels.close':       '**`channels.close(ch Channel)`** — Close a channel.',
  'channels.try_send':    '**`channels.try_send(ch Channel, value int) -> bool`** — Non-blocking send; returns false if full.',
  'channels.try_receive': '**`channels.try_receive(ch Channel) -> (int, bool)`** — Non-blocking receive; returns value and success.',

  // @mem
  'mem.arena':    '**`mem.arena(size int) -> Arena`** — Create an arena with the given byte capacity.',
  'mem.destroy':  '**`mem.destroy(arena Arena)`** — Destroy an arena and free its memory.',
  'mem.reset':    '**`mem.reset(arena Arena)`** — Reset an arena, reclaiming all allocations without freeing.',
  'mem.usage':    '**`mem.usage(arena Arena) -> int`** — Return the number of bytes currently used.',
  'mem.init':     '**`mem.init(arena Arena, Type) -> ^Type`** — Allocate zero-initialized value in the arena.',
  'mem.alloc':    '**`mem.alloc(arena Arena, value T) -> ^T`** — Allocate a copy of value in the arena.',
  'mem.make':     '**`mem.make(arena Arena, Type) -> ^Type`** — Allocate zero-initialized value in arena.',
  'mem.free':     '**`mem.free(arena Arena)`** — Free an arena (alias for destroy).',
  'mem.size_of':  '**`mem.size_of(Type) -> int`** — Size of type in bytes.',
  'mem.raw_copy': '**`mem.raw_copy(dest ptr, src ptr, n int)`** — Copy n bytes from src to dest.',
  'mem.zero':     '**`mem.zero(p ptr, n int)`** — Zero out n bytes at p.',
  'mem.fill':     '**`mem.fill(p ptr, value int, n int)`** — Set n bytes at p to value.',

  // @atomic
  'atomic.load':         '**`atomic.load(ptr ^int) -> int`** — Atomically load a value.',
  'atomic.store':        '**`atomic.store(ptr ^int, val int)`** — Atomically store a value.',
  'atomic.add':          '**`atomic.add(ptr ^int, val int) -> int`** — Atomic add; returns previous value.',
  'atomic.sub':          '**`atomic.sub(ptr ^int, val int) -> int`** — Atomic subtract; returns previous value.',
  'atomic.exchange':     '**`atomic.exchange(ptr ^int, val int) -> int`** — Atomic swap; returns previous value.',
  'atomic.cas':          '**`atomic.cas(ptr ^int, expected int, desired int) -> bool`** — Compare-and-swap.',
  'atomic.and':          '**`atomic.and(ptr ^int, val int) -> int`** — Atomic bitwise AND; returns previous value.',
  'atomic.or':           '**`atomic.or(ptr ^int, val int) -> int`** — Atomic bitwise OR; returns previous value.',
  'atomic.xor':          '**`atomic.xor(ptr ^int, val int) -> int`** — Atomic bitwise XOR; returns previous value.',
  'atomic.spinlock':     '**`atomic.spinlock() -> SpinLock`** — Create a new spinlock.',
  'atomic.spin_lock':    '**`atomic.spin_lock(lk SpinLock)`** — Acquire a spinlock.',
  'atomic.spin_trylock': '**`atomic.spin_trylock(lk SpinLock) -> bool`** — Try to acquire; returns true if acquired.',
  'atomic.spin_unlock':  '**`atomic.spin_unlock(lk SpinLock)`** — Release a spinlock.',
  'atomic.fence':        '**`atomic.fence()`** — Full memory barrier (sequential consistency).',

  // @fmt
  'fmt.printf':       '**`fmt.printf(format string, ...args T)`** — Print formatted string to stdout.',
  'fmt.printfln':     '**`fmt.printfln(format string, ...args T)`** — Print formatted string to stdout with newline.',
  'fmt.eprintf':      '**`fmt.eprintf(format string, ...args T)`** — Print formatted string to stderr.',
  'fmt.eprintfln':    '**`fmt.eprintfln(format string, ...args T)`** — Print formatted string to stderr with newline.',
  'fmt.sprintf':      '**`fmt.sprintf(format string, ...args T) -> string`** — Return formatted string.',
  'fmt.sprintfln':    '**`fmt.sprintfln(format string, ...args T) -> string`** — Return formatted string with newline.',
  'fmt.format':       '**`fmt.format(format string, ...args T) -> string`** — Return formatted string.',
  'fmt.pad_left':     '**`fmt.pad_left(s string, width int, ch char) -> string`** — Pad string on the left.',
  'fmt.pad_right':    '**`fmt.pad_right(s string, width int, ch char) -> string`** — Pad string on the right.',
  'fmt.center':       '**`fmt.center(s string, width int, ch char) -> string`** — Center string within width.',
  'fmt.int_to_hex':   '**`fmt.int_to_hex(n int) -> string`** — Format integer as lowercase hexadecimal.',
  'fmt.int_to_binary':'**`fmt.int_to_binary(n int) -> string`** — Format integer as binary.',
  'fmt.int_to_octal': '**`fmt.int_to_octal(n int) -> string`** — Format integer as octal.',
  'fmt.float_fixed':  '**`fmt.float_fixed(f float, decimals int) -> string`** — Format float with fixed decimal places.',
  'fmt.float_sci':    '**`fmt.float_sci(f float) -> string`** — Format float in scientific notation.',

  // @strconv
  'strconv.to_int':      '**`strconv.to_int(s string, base int = 10) -> (int, Error)`** — Parse string as signed integer.',
  'strconv.to_uint':     '**`strconv.to_uint(s string, base int = 10) -> (uint, Error)`** — Parse string as unsigned integer.',
  'strconv.to_float':    '**`strconv.to_float(s string) -> (float, Error)`** — Parse string as floating-point.',
  'strconv.to_bool':     '**`strconv.to_bool(s string) -> (bool, Error)`** — Parse string as boolean.',
  'strconv.from_int':    '**`strconv.from_int(n int) -> string`** — Convert integer to decimal string.',
  'strconv.from_uint':   '**`strconv.from_uint(n uint) -> string`** — Convert unsigned integer to decimal string.',
  'strconv.from_float':  '**`strconv.from_float(f float) -> string`** — Convert float to string.',
  'strconv.from_bool':   '**`strconv.from_bool(b bool) -> string`** — Convert boolean to "true" or "false".',
  'strconv.is_numeric':  '**`strconv.is_numeric(s string) -> bool`** — True if string is a valid numeric representation.',
  'strconv.is_integer':  '**`strconv.is_integer(s string) -> bool`** — True if string is a valid integer.',
};

// ---------------------------------------------------------------------------
// Hover documentation
// ---------------------------------------------------------------------------

export const DOCS: Record<string, string> = {
  // --- Keywords ---
  'mut': '**`mut`** — Declares a mutable variable.\n\n```gray\nmut x int = 42\nmut name string = "hello"\n```',
  'const': '**`const`** — Declares an immutable constant or a named struct/enum type.\n\n```gray\nconst PI float = 3.14159\nconst Point struct { x int; y int }\n```',
  'if': '**`if`** — Conditional branch. Branches on a boolean expression.\n\n```gray\nif x > 10 {\n    println("big")\n} otherwise {\n    println("small")\n}\n```',
  'otherwise': '**`otherwise`** — The else branch of an `if` or `when` statement. Identical to `else`.',
  'else': '**`else`** — Alias for `otherwise`. The default branch of an `if` or `when` statement.',
  'when': '**`when`** — Pattern-matching switch. Compares a value against a list of cases.\n\n```gray\nwhen x {\n    is 1 { println("one") }\n    is 2 { println("two") }\n    default { println("other") }\n}\n```',
  'is': '**`is`** — Used inside `when` to introduce a match arm.',
  'default': '**`default`** — The fallback arm of a `when` expression.',
  'for': '**`for`** — Range-based loop.\n\n```gray\nfor i in range(0, 10) {\n    println(i)\n}\n```',
  'for_each': '**`for_each`** — Iterates over every element of a collection.\n\n```gray\nfor_each item in items {\n    println(item)\n}\n```',
  'while': '**`while`** — Loop that runs while a condition is true. Alias for `as_long_as`.\n\n```gray\nwhile x > 0 {\n    x--\n}\n```',
  'as_long_as': '**`as_long_as`** — Loop that runs while a condition is true. Identical to `while`.',
  'loop': '**`loop`** — Infinite loop. Use `break` to exit.\n\n```gray\nloop {\n    if done { break }\n}\n```',
  'break': '**`break`** — Exits the innermost loop.',
  'continue': '**`continue`** — Skips to the next iteration of the innermost loop.',
  'return': '**`return`** — Returns a value from a function.\n\n```gray\ndo add(a int, b int) -> int {\n    return a + b\n}\n```',
  'do': '**`do`** — Declares a function (with or without a return type).\n\n```gray\ndo main() {\n    println("Hello, Grayscale!")\n}\n\ndo add(a int, b int) -> int {\n    return a + b\n}\n```',
  'func': '**`func`** — Function type for references and parameters.\n\n```gray\nconst f func(int) -> int = ()double\n```',
  'struct': '**`struct`** — Declares a user-defined composite type.\n\n```gray\nconst Point struct {\n    x int\n    y int\n}\n```',
  'enum': '**`enum`** — Declares a set of named constants.\n\n```gray\nconst Direction enum {\n    NORTH\n    EAST\n    SOUTH\n    WEST\n}\n```',
  'import': '**`import`** — Imports a standard library module.\n\n```gray\nimport @math\nimport @io\n```',
  'using': '**`using`** — Imports a module\'s symbols into the current scope.\n\n```gray\nimport @math using *\n```',
  'use': '**`use`** — Used with `import` to bring symbols into scope.',
  'new': '**`new`** — Allocates a zero-initialized struct on the arena and returns a pointer.\n\n```gray\nmut p ^Point = new(Point)\n```',
  'private': '**`private`** — Restricts visibility of a function or declaration to the current file.',
  'cast': '**`cast`** — Explicit type conversion.\n\n```gray\nmut n i32 = cast(myInt, i32)\n```',
  'in': '**`in`** — Tests membership in a collection.\n\n```gray\nif 5 in numbers { println("found") }\n```',
  'not_in': '**`not_in`** — Tests non-membership in a collection.\n\n```gray\nif 5 not_in numbers { println("missing") }\n```',
  'range': '**`range`** — Creates an integer range for iteration.\n\n```gray\nfor_each i in range(0, 10) { println(i) }\nfor_each i in range(0, 10, 2) { println(i) }  // step 2\n```',
  'or': '**`or`** — Error-propagation operator or else-if branch.\n\n```gray\nmut val = risky() or { return }\n\nif x < 0 {\n    println("negative")\n} or x == 0 {\n    println("zero")\n}\n```',
  'or_return': '**`or_return`** — Returns early if the expression is an Error.',
  'ensure': '**`ensure`** — Deferred cleanup. Runs when the surrounding function exits.\n\n```gray\nensure cleanup()\n```',
  'true': '**`true`** — Boolean literal representing the true value.',
  'false': '**`false`** — Boolean literal representing the false value.',
  'nil': '**`nil`** — Represents the absence of a value (null pointer).',
  'bit_and': '**`bit_and`** — Bitwise AND operator.\n\n```gray\nmut result = a bit_and b\n```',
  'bit_or': '**`bit_or`** — Bitwise OR operator.\n\n```gray\nmut result = a bit_or b\n```',
  'bit_xor': '**`bit_xor`** — Bitwise XOR operator.\n\n```gray\nmut result = a bit_xor b\n```',
  'bit_not': '**`bit_not`** — Bitwise NOT (complement) prefix operator.\n\n```gray\nmut result = bit_not a\n```',
  'bit_shift_left': '**`bit_shift_left`** — Left shift operator.\n\n```gray\nmut result = 1 bit_shift_left 3  // 8\n```',
  'bit_shift_right': '**`bit_shift_right`** — Right shift operator.\n\n```gray\nmut result = 16 bit_shift_right 1  // 8\n```',

  // --- Types ---
  'int': '**`int`** — 64-bit signed integer. Range: -2^63 to 2^63-1. Overflow-checked at runtime.\n\n```gray\nmut x int = 42\n```',
  'uint': '**`uint`** — 64-bit unsigned integer. Range: 0 to 2^64-1. Overflow-checked at runtime.\n\n```gray\nmut count uint = 100\n```',
  'float': '**`float`** — 64-bit IEEE 754 double-precision floating-point.\n\n```gray\nmut pi float = 3.14159\n```',
  'string': '**`string`** — UTF-8 encoded byte sequence. `len()` returns byte length; use `char_count()` for character count.\n\n```gray\nmut s string = "hello"\n```',
  'bool': '**`bool`** — Boolean type. Values: `true` or `false`.',
  'char': '**`char`** — Single character. Convertible to `int` codepoint via `int(c)`.',
  'byte': '**`byte`** — 8-bit unsigned integer (0-255). Useful for raw binary data.',
  'Error': '**`Error`** — Error type returned from functions that can fail. Create with `error("message")`.',
  'map': '**`map`** — Unordered key-value collection. The `map` keyword is optional: `[string:int]` and `map[string:int]` are identical.\n\n```gray\nmut ages [string:int] = {"alice": 30}\n```',
  'i8': '**`i8`** — 8-bit signed integer. Range: -128 to 127.',
  'i16': '**`i16`** — 16-bit signed integer. Range: -32,768 to 32,767.',
  'i32': '**`i32`** — 32-bit signed integer. Range: -2^31 to 2^31-1.',
  'i64': '**`i64`** — 64-bit signed integer. Same as `int` but explicitly sized.',
  'i128': '**`i128`** — 128-bit signed integer (struct-based). Construct with `i128(value)`.',
  'i256': '**`i256`** — 256-bit signed integer (struct-based). Construct with `i256(value)`.',
  'u8': '**`u8`** — 8-bit unsigned integer. Range: 0 to 255.',
  'u16': '**`u16`** — 16-bit unsigned integer. Range: 0 to 65,535.',
  'u32': '**`u32`** — 32-bit unsigned integer. Range: 0 to 2^32-1.',
  'u64': '**`u64`** — 64-bit unsigned integer. Same as `uint` but explicitly sized.',
  'u128': '**`u128`** — 128-bit unsigned integer (struct-based). Construct with `u128(value)`.',
  'u256': '**`u256`** — 256-bit unsigned integer (struct-based). Construct with `u256(value)`.',
  'f32': '**`f32`** — 32-bit IEEE 754 single-precision floating-point.',
  'f64': '**`f64`** — 64-bit IEEE 754 double-precision floating-point. Equivalent to `float`.',

  // --- Builtins ---
  'println': '**`println(value)`** — Prints a value followed by a newline. Accepts any type.',
  'print': '**`print(value)`** — Prints a value without a trailing newline. Accepts any type.',
  'eprintln': '**`eprintln(value)`** — Prints a value to stderr with a newline.',
  'eprint': '**`eprint(value)`** — Prints a value to stderr without a newline.',
  'input': '**`input() -> string`** — Reads a line from stdin and returns it as a string.',
  'len': '**`len(collection) -> int`** — Returns the length of an array, map, or string (byte length for strings).',
  'type_of': '**`type_of(value) -> string`** — Returns the Grayscale type name as a string (e.g. `"int"`, `"string"`).',
  'size_of': '**`size_of(Type) -> int`** — Returns the size of a type in bytes.',
  'copy': '**`copy(value) -> T`** — Creates a deep copy of any value.',
  'ref': '**`ref(variable) -> ref<T>`** — Creates a transparent reference (alias) to a variable.',
  'addr': '**`addr(variable) -> ^T`** — Returns the memory address of a variable as a pointer.',
  'error': '**`error(message string) -> Error`** — Creates an Error value with the given message.',
  'assert': '**`assert(condition bool [, message string])`** — Panics with P0075 if condition is false. Message is optional.',
  'panic': '**`panic(message string)`** — Terminates the program immediately with an error message.',
  'exit': '**`exit(code int)`** — Exits the program with the given status code.',
  'to_char': '**`to_char(s string, index int) -> int`** — Returns the Unicode codepoint at character position `index`.',
  'char_count': '**`char_count(s string) -> int`** — Returns the number of Unicode characters (not bytes) in a string.',
  'c_string': '**`c_string(ptr ^u8) -> string`** — Converts a C `char*` pointer to a Grayscale string (C interop).',
  'embed': '**`embed(path string) -> string`** — Reads a file at compile time and bakes its contents into the binary.',
  'sleep_s': '**`sleep_s(seconds int)`** — Sleeps for the given number of seconds.',
  'sleep_ms': '**`sleep_ms(ms int)`** — Sleeps for the given number of milliseconds.',
  'sleep_ns': '**`sleep_ns(ns int)`** — Sleeps for the given number of nanoseconds.',

  // --- Attributes ---
  '#doc': '**`#doc("...")`** \u2014 Documentation metadata for functions, structs, enums, and file-scope variables. Consumed by `gray doc`.\n\n```gray\n#doc("Adds two numbers")\ndo add(a int, b int) -> int {\n    return a + b\n}\n```',
  '#json': '**`#json`** \u2014 Enables JSON serialization for a struct. Required by `json.parse()` and `json.stringify()`.\n\nSupported field types: `int`, `uint`, `float`, `string`, `bool`, plus nested `#json` structs. `#json` structs cannot have default field values.\n\n```gray\n#json\nconst Person struct {\n    name string\n    age int\n}\n```',
  '#flags': '**`#flags`** \u2014 Marks an enum as a bitflag set. Variant values become powers of 2 instead of auto-incrementing from 0.\n\n```gray\n#flags\nconst Permissions enum {\n    READ      // 1\n    WRITE     // 2\n    EXECUTE   // 4\n}\n```',
  '#strict': '**`#strict`** \u2014 Applied to a `when` block, requires every variant of the matched enum to be handled.\n\n```gray\n#strict\nwhen dir {\n    is .NORTH { }\n    is .EAST  { }\n    is .SOUTH { }\n    is .WEST  { }\n}\n```',
  '#discard': '**`#discard`** \u2014 Marks a function whose return value may safely be ignored by callers.\n\nWithout `#discard`, calling a non-void function as a bare statement produces **E5011** (return value not used). With it, callers may drop the result.\n\n```gray\n#discard\ndo log(msg string) -> int {\n    println(msg)\n    return 0\n}\n\ndo main() {\n    log("hello")   // no E5011\n}\n```\n\nApplies to plain functions and struct functions. Cannot be applied to structs, enums, or variables (E2002), nor to void functions (E5042).',

  // --- Stdlib modules ---
  'arrays': '**`@arrays`** — Array utilities: `append`, `remove`, `contains`, `reverse`, `sort`, `slice`, `flatten`, `map`, `filter`, `reduce`, `any`, `all`, etc.',
  'strings': '**`@strings`** — String manipulation: `split`, `join`, `trim`, `contains`, `starts_with`, `ends_with`, `replace`, `to_upper`, `to_lower`, `char_at`, `to_chars`, `from_chars`, etc.',
  'maps': '**`@maps`** — Map utilities: `get_keys`, `get_values`, `has_key`, `remove_key`, `merge`, `is_equal`, etc.',
  'math': '**`@math`** — Math functions: `abs`, `sqrt`, `pow`, `log`, `sin`, `cos`, `tan`, `ceil`, `floor`, `round`, `min`, `max`, `clamp`, `lerp`, etc.',
  'time': '**`@time`** — Time utilities: `now`, `format`, `to_iso`, `date`, `tick`, `elapsed_ms`, `diff`, etc.',
  'random': '**`@random`** — Random number generation: `rand_int`, `rand_float`, `seed`, `choice`, `shuffle`, etc.',
  'json': '**`@json`** — JSON encoding/decoding: `parse`, `stringify`, `encode`, `decode`, `is_valid`, `pretty_print`.',
  'io': '**`@io`** — File and directory I/O: `read_file`, `write_file`, `read_lines`, `file_exists`, `walk`, `glob`, `path_join`, etc.',
  'os': '**`@os`** — OS interaction: `get_env`, `set_env`, `args`, `current_dir`, `exec`, `pid`, `arch`, etc.',
  'http': '**`@http`** — HTTP client: `get`, `post`, `put`, `patch`, `delete`, `head` with custom headers.',
  'crypto': '**`@crypto`** — Cryptographic functions: `sha256`, `md5`, `random_hex`.',
  'encoding': '**`@encoding`** — Base64, hex, and URL encoding/decoding.',
  'uuid': '**`@uuid`** — UUID generation: `generate`, `generate_random`, `generate_time_ordered`, `parse`, `is_valid`, etc.',
  'bytes': '**`@bytes`** — Byte slice operations: `from_string`, `to_string`, `from_hex`, `to_hex`, etc.',
  'binary': '**`@binary`** — Binary read/write: little-endian and big-endian integer/float I/O.',
  'sqlite': '**`@sqlite`** — SQLite database access: `open`, `close`, `exec`, `query`.',
  'server': '**`@server`** — HTTP server: `add_router`, `add_route`, `listen`, `cors`, response builders.',
  'regex': '**`@regex`** — Regular expressions: `is_match`, `find`, `find_all`, `replace`, `split`.',
  'csv': '**`@csv`** — CSV parsing and writing: `parse`, `encode`, `read_file`, `write_file`, `headers`.',
  'net': '**`@net`** — TCP sockets and DNS: `connect`, `listen`, `accept`, `send`, `receive`, `resolve`.',
  'threads': '**`@threads`** — Thread lifecycle: `spawn`, `join`, `detach`, `is_alive`, `sleep`, `yield`.',
  'sync': '**`@sync`** — Synchronization: `mutex`, `lock`, `unlock`, `try_lock`, `destroy`.',
  'channels': '**`@channels`** — Message passing: `open`, `send`, `receive`, `close`, `try_send`, `try_receive`.',
  'mem': '**`@mem`** — Arena memory: `arena`, `destroy`, `reset`, `init`, `alloc`, `make`, `raw_copy`.',
  'atomic': '**`@atomic`** — Lock-free atomics: `load`, `store`, `add`, `cas`, `spinlock`, `fence`.',
  'fmt': '**`@fmt`** — Formatted output: `printf`, `sprintf`, `pad_left`, `pad_right`, `int_to_hex`, `float_fixed`.',
  'strconv': '**`@strconv`** — String conversions: `to_int`, `to_float`, `to_bool`, `from_int`, `is_numeric`, `is_integer`.',
};
