id = "gray"
name = "Grayscale"
version = "0.0.1"
schema_version = 1
authors = ["Marshall Burns"]
description = "Grayscale programming language support: syntax highlighting and LSP"
repository = "https://github.com/SchoolyB/Grayscale"

[grammars.gray]
repository = "https://github.com/SchoolyB/tree-sitter-gray"
rev = "e99979c5e228137127616b8c8d73bcc9fd93e479"

[language_servers.grayls]
language = "Grayscale"
