id = "gray"
name = "Grayscale"
version = "0.0.1"
schema_version = 1
authors = ["Marshall Burns"]
description = "Grayscale programming language support: syntax highlighting and LSP"
repository = "https://github.com/grayscale-lang/Grayscale"

[grammars.gray]
repository = "https://github.com/grayscale-lang/tree-sitter-gray"
rev = "5d26538891b107f92c3f27708c6c11341e89199a"

[language_servers.grayls]
language = "Grayscale"
